title: Qubic's Website
url: "https://qyb225.github.io"
baseurl: ""
description: >
  Qubic 的个人网站

email: qyb225@gmail.com
author: Yibin Qiu
avatar: "https://avatars2.githubusercontent.com/u/17106104?v=4&s=460"
profile: 这辈子怕是学不会 C++ 了
github_username:  qyb225

permalink: /archivers/:title
plugins_dir:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate]