# Site settings
title: Qubic's Website
url: "https://qyb225.github.io"    # the protocol and hostname of your site
baseurl: "" # the prefix of your site uri
#timezone: Asia/Chongqing
description: >
  Qubic 的个人网站

# Your information
email: qyb225@gmail.com
author: Yibin Qiu
avatar: "https://avatars2.githubusercontent.com/u/17106104?v=4&s=460"
profile: 双鸭山大学软件工程在读
github_username:  qyb225

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
